### ISSUE TITLE
As as an App Admin, I want all DokuWiki user accounts moved to Gogs to support migration.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/gogs#10]
_From @bspidel on January 21, 2016 20:54_

Acceptance Criteria:
1 - I can use code at github.com/gogits/gogs/pull/2070/commits
2 - Users can access Gogs without registering.
3 - DokuWiki accounts remain until Door43 looks to Gogs 

_Copied from original issue: unfoldingWord-dev/sysadmin#39_

**Comment by bspidel** [comment]
_From @jag3773 on February 1, 2016 20:48_

Possibly, we could set DokuWiki to query the Gogs user DB via the postgres DB.  Not sure if it is worth the development effort though.

**Comment by jag3773** [comment]
See #12 for setting DW to query gogs user db.

**Comment by jag3773** [comment]
Note, do **not** overwrite any existing users in gogs.
