### ISSUE TITLE
Deploy New Gogs Features to Production

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#100]
@jag3773 commented on [Tue Nov 29 2016](https://github.com/unfoldingWord-dev/door43.org/issues/339)

## Story

As a *user* I want to use the new features built last sprint so that my life rocks on!

## Notes

* [x] Figure out how to add githook to ubn repos

**Comment by richmahn** [comment]
The githook gets into the release at custom/bin and I tried to update the puppet init.pp file to run it, but seems to fail.
