### ISSUE TITLE
As an App Admin, I want DokuWiki content moved to Gogs to minimize manual effort.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/gogs#11]
_From @bspidel on January 21, 2016 22:19_

Acceptance Criteria:
1. - I can see structure as user/lang-project
2. - All dokuwiki markup is converted to gogs markdown

_Copied from original issue: unfoldingWord-dev/sysadmin#41_

**Comment by bspidel** [comment]
_From @jag3773 on February 4, 2016 13:29_

@richmahn Do we have a script somewhere that can convert our DW syntax to MarkDown format?  I'd like to try getting an OBS project moved over to see if it will look as we expect.

**Comment by bspidel** [comment]
_From @jag3773 on February 4, 2016 18:8_

Couple notes, we'll need to split the monolithic language repos into their language-project counterparts.  The following links give information on how to do that while maintaining the version history:
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/
http://blogs.atlassian.com/2014/04/tear-apart-repository-git-way/

**Comment by bspidel** [comment]
_From @jag3773 on February 4, 2016 22:21_

I think we'll want to take the following as our procedure for the move:

* [ ] Split out project from language, as in comment above
* [ ] Push/Create the repo in git.door43.org following the `lang-project` nomenclature
* [ ] Convert to MarkDown (possibly create a tag for this commit as something like "md" ?)

The advantage of doing it this way is that we'll have all the previous revision history using the DW syntax and then we'll have a single commit for the switch to MarkDown.

For resources that are published already, like en-obs, I'd also like to create a tag with the currently published version (v 4 in this case).  That will help facilitate change log creation later on down the road.

**Comment by jag3773** [comment]
I think we want to match https://github.com/unfoldingWord-dev/ts-requirements/wiki/ts.Translator.TargetTranslation#possible-long-term-solution for formatting the names of the repos.  Important part is to use `_` as the separator character.

**Comment by richmahn** [comment]
This is now ready. Once we switch Dokuwiki to using postgres, thus users.auth.php no longer accepting new users, we need to run the script on production to get all users from that file into a SQL file. Then that SQL file needs to be imported into the postgres database that Gogs uses.
