### ISSUE TITLE
Different users with same e-mail causes error on create repositores and user creation from register

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/gogs#120]
We need a fix for how different users can be created with the same email addresses, but then throws an error when doing various actions on a repo (or creating a repo) as that user. This has been discussed in

https://github.com/go-gitea/gitea/issues/13

but doesn't seem to have any work moving forward on it. There should be checking in the code, but also make the field in the database for email be unique for the user table. Possibly should fix this for upstream, even though they have labeled it for v1.1.0 and they don't even have v1.0 yet.

**Comment by phillip-hopper** [comment]
Tested. This appears to have been fixed in up-stream:

* Not able to register using an email that is already taken.
* Not able to create a new user in admin panel using an email that is already taken.
