### ISSUE TITLE
Add Viewer for YAML Files

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#139]
## Story

As a *user* I want to see my manifest file in a pretty form so that I can easily see what information it encodes.

## Notes

We should have a YAML viewer for any file that ends in `.yaml`.  Currently, the `manifest.yaml` file(s) are not processed to produce nice output.

Right now, https://git.door43.org/Door43/en-ta-process/src/master/toc.yaml is working, but https://git.door43.org/Door43/en-obs/src/master/manifest.yaml is not.

**Comment by ethantkoenig** [comment]
@jag3773 For the example that you gave, `manifest.yaml` renders correctly if you remove the comma at the end of the file. Do you have another example of a yaml file that doesn't render properly?

**Comment by ethantkoenig** [comment]
In the case of malformatted YAML files, would it be better to just display them like regular text files? That might make it easier for the user to spot where/how the file is misformatted.

**Comment by jag3773** [comment]
Awesome!  Thanks for spotting that.

Yes, I agree about the display of malformed YAML files.  Is there a chance that we could also highlight the error in the file?  Don't spend more than an hour researching that.  If it's simple to do then we'll create another issue for it, otherwise we'll go without.
