### ISSUE TITLE
Add Support For Renaming Repos (With Redirects)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#140]
## Story

As a *user* I want to be able to rename repositories without breaking the internet so that people don't get lost trying to find my content.

## Notes

Github does this same thing, in the settings there is a rename function.  The software should redirect the old repo name to the new repo name automatically.

First need for this is to make our repos conform to our [naming convention](https://git.door43.org/Door43/registry/src/master/README.md).  For example, we need our 'en-obs' repository to be named 'en_obs'.

**Comment by ethantkoenig** [comment]
Redirects for renamed repos have been merged into upstream, and will reach our fork the next time we bring in changes.
