### ISSUE TITLE
Set Font for Hebrew

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#141]
The Hebrew font on git.door43.org is a bit rough to read.  Let's set the default to [SBL Hebrew](https://www.sbl-site.org/educational/BiblicalFonts_SBLHebrew.aspx) with a fall back to GentiumAlt, then to Noto Sans.

**Comment by ethantkoenig** [comment]
@jag3773 Do you have an example of a repo/page with Hebrew text?

**Comment by jag3773** [comment]
This page has Hebrew on it: https://git.door43.org/Door43/en-uhg/src/master/content/adjective/02.md .

**Comment by ethantkoenig** [comment]
^ I have not forgotten about this; I'm having some trouble getting gitea to send the necessary `.ttf` files to the browser. Will continue investigating.
