### ISSUE TITLE
Duplicate Email Issue

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#142]
Setting up an account allows for an email to be used that has already been used in the system, which later prevents the user from logging in because the email is supposed to be unique.

**Comment by ethantkoenig** [comment]
Now that the latest changes have been merged from upstream, you can't create a new user with an existing email. The only remaining thing is to resolve any existing collisions (once production gets the changes from upstream, of course).

**Comment by phillip-hopper** [comment]
Tested. It is now fixed.

**Comment by jag3773** [comment]
Need to verify that creating a user via the API does not trigger this issue.

**Comment by PhotoNomad0** [comment]
@jag3773 - wanting to test this with ts-android which currently uses ts.door43.org for authentication server. What is the authentication server for aws.door43.org?

**Comment by PhotoNomad0** [comment]
Using aws.door43.org, ts-android now fails when I try to create a new account with existing email address. the api returns a response code of 422 and null data.  Unfortunately we don’t have a helpful error message.
When I change to new email address it goes through.  
So the api looks good.
