### ISSUE TITLE
Ability to upload more than 5 files at a time to a repo

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/gogs#146]
It would be nice if as an end user in github that I could determine the limitation of the files that I can upload to my own repository.

Right now - I am limited to only 5 files at a time. Perhaps a switch that I could toggle to change while I have some 20 or so files to upload to the repo and then toggle the option off when I have completed the uploads. 

If the above is not possible - what about a special request to 'someone' that will allow the temporary permission to upload multiple (more than the limit of 5 as it is now) files.

**Comment by jag3773** [comment]
The limit is currently set to 70.

However, users should be using a Git client if they want to upload lots of files.  SmartGit is a good option.
