### ISSUE TITLE
Test DW Queries against new Gogs RDS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#161]
The user/group queries in DW need to be tested against the new Gogs RDS instance which is MySQL compatible now.

* [ ] Make sure DW IP (and test IP) is allowed to connect
* [ ] Make sure all queries execute properly on test DW server

**Comment by phillip-hopper** [comment]
@jag3773 Apparently I don't have permission to see the RDS instance. That control panel is blank for me.

**Comment by phillip-hopper** [comment]
@jag3773 Also, I'm not finding the queries.

**Comment by phillip-hopper** [comment]
I have verified that the queries will need to be re-written for MySQL.

**Comment by phillip-hopper** [comment]
Queries have been rewritten for MySQL and placed into the DW setup on door43.org.

**Comment by phillip-hopper** [comment]
I was able to get it to work with no changes to PHP code. However, none of the user functions work other than logging in.

Also, the `Comma separated list of tables that should be locked` field in setup __MUST__ be set to a __BOGUS__ table name or else the Admin link is not available for administrators.
