### ISSUE TITLE
Deploy New Build to AWS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#165]
## Notes

Trying building with latest Go, v 1.8.  If that fails to compile, try v 1.7.

Once built, the linux_amd64 binary needs uploaded as a new release to our Gogs repo.

After that, the update Gogs command on the AWS server needs to be run via puppet.

**Comment by richmahn** [comment]
New release: https://github.com/unfoldingWord-dev/gogs/releases/tag/v1.1.0
