### ISSUE TITLE
Fix Organization Webhook to Trigger when something is forked into it

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#169]
## Story

As a *developer* I want the organization's webhook to fire when a new repo is forked into said organization so that I know something changed and can use the data.

Scenario: User_A likes My_Cool_Repo and forks it into Org_A, the webhook fires and and everyone is happy.

Our Scenario: We receive a source text request which we fulfill by forking the source repository into our Door43-Catalog repository, which fires the webhook and starts an update of our API v3 catalog.

**Comment by ethantkoenig** [comment]
Right now, the only supported webhook events are
- "create": when a branch or tag is created
- "push": push to a repository
- "pull": pull request opened, closed, reopened, edited, assigned, unassigned, label updated, label cleared, or synchronized

I've created a PR upstream (https://github.com/go-gitea/gitea/pull/1663) to support webhooks for "repository" events (repository created or deleted in an org). An organization forking a repository is just a special case of the "repository" event.

If there are any other webhooks events you need implemented, let me know. Github, for instance, supports a fairly comprehensive set of events (https://developer.github.com/webhooks/#events)

**Comment by ethantkoenig** [comment]
@jag3773. This webhook was implemented in https://github.com/go-gitea/gitea/pull/1663, which was included in the 1.4.0 release. Is it not working as expected?

**Comment by jag3773** [comment]
I haven't tried, which is why I stuck that label on it.  Can you verify that this *is* working?
