### ISSUE TITLE
Update YAML Viewer

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#170]
This is an update on #48 .

It would be a lot friendlier if our YAML viewer worked liked Githubs.  See https://github.com/unfoldingWord-dev/door43.org/blob/develop/.travis.yml .  That is a lot easier to read than https://git.door43.org/Door43/en-obs/src/master/manifest.yaml.

**Comment by ethantkoenig** [comment]
Is upstream's rendering of YAML files good enough for us (see https://try.gitea.io/ethantkoenig/sandbox/src/master/stuff.yaml)?

**Comment by richmahn** [comment]
I'll try turning off my YAML renderer, but to do so I think that links won't work to pages in the TOC.yaml files.

**Comment by richmahn** [comment]
@jag3773 I thought we wanted the YAML view to be a bunch of tables with links to files in the repo like this: https://git.door43.org/Door43/en-ta-translate-vol1/src/master/toc.yaml

If we change it to be just a viewer like seeing .travis.yaml, we will lose the tables and links that we put into place in issues #48 and #62. Should we ONLY use my YAML parsers/table viewer for toc.yaml files?

**Comment by jag3773** [comment]
@richmahn Yes, if we can only use your custom renderer for the toc.yaml files that would be great.

**Comment by ethantkoenig** [comment]
Better?

![image](https://cloud.githubusercontent.com/assets/8990880/25978723/08a7d6f4-3692-11e7-8514-8cf39952db95.png)

**Comment by richmahn** [comment]
@ethantkoenig How does that effect yaml files like https://git.door43.org/Door43/en-ta-translate-vol1/src/master/toc.yaml (tables which their slugs link to the files)

**Comment by ethantkoenig** [comment]
@richmahn If we still use the custom rendering for toc.yml, then not at all. This would just be an improvement on the default YAML renderer in upstream.

**Comment by richmahn** [comment]
@jag3773 @ethantkoenig @neutrinog That's where we then need to decide if the `IsYaml(filename)` check is to be changed to `IsTOCYaml(filename)` or something of that nature and only process toc.yaml files, or if we are going to do away with toc.yaml files all together. If we stick with using toc.yaml files, I suggest that we only process toc.yaml files, unless here are other yaml files that are also listing content?

**Comment by ethantkoenig** [comment]
FYI: The "better" rendering of YAML files (above screenshot) has been merged into upstream (https://github.com/go-gitea/gitea/pull/1764)

**Comment by richmahn** [comment]
@ethantkoenig We do want to use that Ethan, just we still have to preserve the tabular view of linked slugs for toc.yaml and config.yaml files. So I will change what I did to just work with those files. All other YAML files will just use however gitea shows such files.
