### ISSUE TITLE
Final Testing of AWS Gogs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#171]
Run (manually) through items in:

https://github.com/unfoldingWord-dev/gogs/wiki/Items-for-Acceptance-Testing

Putting items here and will check those that pass, or make a note for those that don't:

* [x] Avatars persist across updates - **_FAILS, see comment below_**
* [x] "Code" is renamed as "Files" in top left tab of repo, with a font awesome file icon
* [x] Options not available if not logged in: explore, private repos
* [x] Options available if logged in: explore
* [x] Access to private repos is restricted
* [x] License file is created in new repos as `LICENSE.md` with correct CC BY-SA text
* [x] Scrub tool functions for a repo
* [x] Google Analytics code present
* [x] Webhook(s) are trigged on push and/or web editor commit
* [x] TOC yaml files link to the correct places within the repo
* [x] Create private repo option disabled for regular users (unless user is an admin)
* [x] Able to delete a user
* [x] Any user can fork from any public repo
* [x] Any user can create a PR for any public repo
* [x] Emails are sent to appropriate parties on appropriate actions
  * [x] When someone is assigned an issue, they are emailed
  * [x] Comments on issues send emails to parties included on that issue (owner, assignee, commentors get emails)
  * [x] New user registration sends email to user
* [x] Web editor works
* [x] Battery of tests against API
  * [x] Create repo
  * [x] Get repo
  * [x] Delete repo
  * [x] Get list of all repos
  * [x] Get list of repos for user
  * [x] Check that "username" is in output of repo list
* [x] Log in, log out.
* [x] Register new user
* [ ] User can cancel registration - all info and repos deleted
* [x] Create public repos
* [x] Edit file formats: .txt, .md, .usfm, .json, .yml/yaml
* [x] Watch/unwatch
* [x] Star/unstar
* [x] Download zip, gz, individual file, from branch/tag/commit
* [x] Clone and push to repo
  * [x] Over SSH
  * [x] Over HTTPS

**Comment by richmahn** [comment]
For the first one, that avatars persist across migration/upgrade, I found a migration that was added is making everyone's avatar the same. I couldn't figure out a quick fix, other than when we run gitea the first time to do the migrations, to rename /mnt/git/gogs-avatars to something else, run gitea and then put the gogs-avatars directory back.

https://github.com/go-gitea/gitea/issues/1234

**Comment by richmahn** [comment]
There's a fix now to make sure avatars are carried over. Uncomment the AVATAR_DIR line in the app.ini line after the first run of the gitea binary.

**Comment by richmahn** [comment]
I don't see a way for a user to cancel registration (unverified account), and once verified, if they want to delete their account, but have repos, they have to delete their repos first, so deleting an account doesn't delete repos for them.
