### ISSUE TITLE
Issue Search Doesn't Work

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#172]
Searching for issues at https://aws.door43.org/Door43/en-uhg/issues doesn't work.  For instance, searching for "glossary" (https://aws.door43.org/Door43/en-uhg/issues?type=all&state=open&labels=0&milestone=0&assignee=0&q=glossary) only returns 1 result where as there are more than 1 issues with the word "glossary in their title.

**Comment by ethantkoenig** [comment]
I recall seeing a related upstream issue about a month ago, but can't seem to find it. I'll let you know if I stumble across it.

**Comment by ethantkoenig** [comment]
I found the upstream issue, but after poking after I think it's unrelated to this. From what I can tell, the problems is that not all of the issues were added to the issues indexer, and the search does not find issues that are not added to the indexer.

To confirm, could you add a milestone to an issue that should show up but doesn't (say https://aws.door43.org/Door43/en-uhg/issues/201, it's fine if you immediately remove the milestone after adding it), and see if it starts showing up? It has to be on a pre-existing issue; newly-added issues show up fine in the search.

**Comment by richmahn** [comment]
This was fixed by deleting the /mnt/git/indexers directory and restarting gitea.

**Comment by richmahn** [comment]
We may need to remember to do this again when we do another full migration/deploy from git.door43.org
