### ISSUE TITLE
Set Emails to Hidden

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#176]
Set all current to hidden.

Make hidden the default for new.

**Comment by jag3773** [comment]
@phillip-hopper I updated the config file to have these settings:

```
DEFAULT_KEEP_EMAIL_PRIVATE = true
NO_REPLY_ADDRESS = noreply.door43.org
```
I would still like to check in to making all current accounts set to private.

**Comment by richmahn** [comment]
@jag3773 That's been updated in the database table user.keep_email_private for all users, set to 1. So all existing users have their email set to private, and all new users will have their email private. Tested this.

**Comment by phillip-hopper** [comment]
Wow, this is going a lot easier than I could have hoped! Keep up the good work guys!
