### ISSUE TITLE
500 Error on Dashboard

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#179]
@mondele commented on [Mon Mar 06 2017](https://github.com/unfoldingWord-dev/gogs-custom/issues/7)

When a user is a member of a deleted group (and possibly at other times) there is a 500 error when going to the Dashboard page.

---

@mondele commented on [Mon May 01 2017](https://github.com/unfoldingWord-dev/gogs-custom/issues/7#issuecomment-298354995)

Is there any hope of this being fixed?

**Comment by jag3773** [comment]
This issue is resolved now.

However, for users that already have this problem we will need to clean the database manually.

**Comment by jag3773** [comment]
@richmahn user `jdwood` currently has this problem, he cannot load his dashboard page.  Can you dive into the database and see where the disconnect is that is causing this problem?

**Comment by ethantkoenig** [comment]
See https://github.com/unfoldingWord-dev/gogs/issues/136

**Comment by richmahn** [comment]
@jag3773 Yes, will look

**Comment by richmahn** [comment]
There were three org_user relations that had org ids that no longer existed. Wasn't really clear what they were, except one did have a team called "Eurasia-Tech" if that is any clue to what use to exist. Would be nice to know how they delete the org.  Anyway, I cleaned it up, removing the org_user and team entries for those bad orgs.
