### ISSUE TITLE
Update Branding to DCS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#181]
## Story

As a *user* I want to know what to call the site at git.door43.org so that I can reference it easily.

## Notes

The site at git.door43.org is called the **Door43 Content Service**.  The abbreviation is **DCS**.  Everywhere that is appropriate we need to refer to the site and code as DCS.  Sometimes the long version, Door43 Content Service, may be used.

These locations need updated:

* [x] New DCS logo should be used
* [x] Home page should refer to itself correctly.
* [x] About page should be the same as Home page.

The README in this repo needs to refer to itself correctly.

**Comment by Thajny** [comment]
![dcs_dark](https://cloud.githubusercontent.com/assets/21183377/26694143/1834324e-46cc-11e7-8039-43579b6c01ef.png)

![dcs_light](https://cloud.githubusercontent.com/assets/21183377/26694142/182f2e8e-46cc-11e7-8618-e642e32e672c.png)

**Comment by Thajny** [comment]
[DCS svg.zip](https://github.com/unfoldingWord-dev/gogs/files/1045677/DCS.svg.zip)

**Comment by richmahn** [comment]
Is there a small square logo that we can use in the upper left when logged in and for the favicon?

**Comment by richmahn** [comment]
@jag3773 ^^^

**Comment by richmahn** [comment]
Favicon from @Thajny 
![favicon](https://user-images.githubusercontent.com/2839925/26882867-2ef9b150-4bce-11e7-8a65-9b63c89a7682.png)

**Comment by richmahn** [comment]
Note, there is a new Wiki page to use DCS everywhere on git.door43.org, but won't be used until this update is put into production, as it uses a new URL for the "About DCS" at the top:

https://git.door43.org/Door43/pages/wiki/Welcome-to-Door43-Content-Service%21

This one should be edited for future changes, and it is the one that is similar to the "Home" page when not logged in.

**Comment by phillip-hopper** [comment]
@Thajny, @richmahn,  Have you considered the issue of favicon size and compatibility? This S.O. post is a good place to start: https://stackoverflow.com/a/23734416/4650008.

**Comment by richmahn** [comment]
Actually have an .svg file from @Thajny but github won't let me upload. It's in at https://team43.slack.com/?redir=%2Farchives%2FG1T8J0CET%2Fp1496843800134565

**Comment by richmahn** [comment]
@phillip-hopper Shouldn't this then be an issue with upstream gitea as well? Don't think they do anything more than a 30x30 favicon.png file.

**Comment by richmahn** [comment]
@phillip-hopper Actually their icon, https://try.gitea.io/img/favicon.png is 143x143. @Thajny can we get a bigger resolution at least? That is why I asked for a 200x200, but 143x143 would be fine.

**Comment by phillip-hopper** [comment]
@richmahn Maybe our target audience is such that this won't matter, I'm not sure. It may be a good idea to consider the nuances of how the site will appear on different devices, beyond just the page layout.

**Comment by richmahn** [comment]
@phillip-hopper Understandable. I think we should at least keep it to why Gitea decided on 143x143 (not sure why the magic number), as maybe that at least handles different devices and lets the image tags and browser tab resize as needed.

**Comment by phillip-hopper** [comment]
@richmahn & @Thajny, this is the list of icons from youtube.com, just so we are all on the same page:
```html
<link rel="shortcut icon" href="https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico" type="image/x-icon">
<link rel="icon" href="/yts/img/favicon_32-vfl8NGn4k.png" sizes="32x32">
<link rel="icon" href="/yts/img/favicon_48-vfl1s0rGh.png" sizes="48x48">
<link rel="icon" href="/yts/img/favicon_96-vfldSA3ca.png" sizes="96x96">
<link rel="icon" href="/yts/img/favicon_144-vflWmzoXw.png" sizes="144x144">
```

**Comment by richmahn** [comment]
143x143 like Gitea has: 
![dcs favicon 143px](https://user-images.githubusercontent.com/2839925/26934235-651b537e-4c9b-11e7-9939-ceaa484cb7c2.png)

**Comment by richmahn** [comment]
@phillip-hopper I'm more for making this change in upstream so we don't have conflicts in the header here. Then we just change the favicon_42.png or whatever, which is less likely to changein upstream.
