### ISSUE TITLE
Move tmp to /tmp

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#185]
We want to have our DCS server use /tmp for the temporary directory so that it doesn't stress the EBS anymore than it needs to.

**Comment by phillip-hopper** [comment]
@jag3773 or @richmahn, this change is to the `custom/conf/app.ini` file, which is not in a repository that I could find. Where does this change belong?

**Comment by richmahn** [comment]
@phil: It's on the AWS server itself, in the /config directory. Do you have access? @jag3773 will have to give you root access vi ssh if not.

**Comment by richmahn** [comment]
@phil: I just went ahead and made the change.

**Comment by richmahn** [comment]
@phillip-hopper: Actually I wasn't able to get data/tmp/local-repo to go to /tmp. Evenif you symlink data/tmp to /tmp it gets removed when you restart gogs. Are you able to figure out a solution to change where local-repo is located? That is what gets written to the most, but is just temporary work space.

**Comment by richmahn** [comment]
uploads, avatars, and sessions all have place to set the directory, but not local-repo

**Comment by richmahn** [comment]
@jag3773 @phillip-hopper The data/ directory is only used now for data/sessions and data/tmp/local-repo. We could symlink that dir to /tmp or /tmp/data. What do you think?

**Comment by phillip-hopper** [comment]
@richmahn What changes did you make on AWS?

**Comment by richmahn** [comment]
I made the `[repository.upload] TEMP_PATH=/tmp/gogs-repo-uploads`. That's about all there is that you can change....just a temp place to put the uploaded files for a repo before they are added to the repo.

**Comment by phillip-hopper** [comment]
PR has been merged into upstream gitea for this (https://github.com/go-gitea/gitea/pull/1881).

These changes need to be made to the custom `app.ini` file:
```ini
[repository.upload]
; Path for uploads. Defaults to `data/tmp/uploads`
TEMP_PATH = /tmp/gitea-repo-uploads

[repository.local]
; Path for uploads. Defaults to `tmp/local-repo`
LOCAL_COPY_PATH = /tmp/gitea-repo-local
```

**Comment by richmahn** [comment]
@phillip-hopper Ok, didn't see a repository.local section in the upstream app.ini file. WIll look to see if we have it.

**Comment by richmahn** [comment]
Ah, you made the addition...cool. Will pull it.

**Comment by richmahn** [comment]
@phillip-hopper cherry-picked your change into our gogs (https://github.com/unfoldingWord-dev/gogs/commits/develop) and updated app.ini on aws to your specs.
