### ISSUE TITLE
500 Error when opening Collaboration pane

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/gogs#193]
I get a 500 error when opening the collaboration pane for my repository. https://git.door43.org/Door43/en_uhg/settings/collaboration

It may be that this is related to the deleted groups bug.

**Comment by ethantkoenig** [comment]
Could someone provide a log?

**Comment by richmahn** [comment]
The log shows this when going to that page:

```2017/06/07 01:36:15 [...ters/repo/setting.go:400 Collaboration()] [E] GetCollaborators: user does not exist [uid: 5667, name: , keyid: 0]```

**Comment by richmahn** [comment]
So right, there is no user 5667. 

```mysql> select * from collaboration where user_id =  5667;
+----+---------+---------+------+
| id | repo_id | user_id | mode |
+----+---------+---------+------+
| 84 |    4430 |    5667 |    2 |
+----+---------+---------+------+
1 row in set (0.00 sec)```

So looks like we are not deleting the user from collaboration somewhere. @mondele Was this user maybe deleted through the old DW door43.org? We then need to delete from this table too I guess when deleted.

**Comment by richmahn** [comment]
@mondele You can visit that page now. I deleted the bad user from the collaboration table. I'll put a fix into the DW delete user SQL to make sure they are deleted here too.

**Comment by ethantkoenig** [comment]
Could someone provide a log?

**Comment by richmahn** [comment]
Added `DELETE FROM collaboration WHERE user_id = %{uid};` to the DW code that deletes users from the DB.

**Comment by mondele** [comment]
I don't know if this information is still needed, but the user is Chapel Presson.

**Comment by richmahn** [comment]
@mondele Do you know how he got deleted?

**Comment by mondele** [comment]
Unfortunately, no. I could ask Chapel if you like.

John Wood
john_wood@wycliffeassociates.org<mailto:john_wood@wycliffeassociates.org>

[cid:6BA4AD1D-02BF-4D07-85FC-1537323F007B@cyclops.homelinux.net]
Help Desk Supervisor
@jwood on #slack
archistratus on
[cid:AA1E8E39-BD58-48C2-AF4E-8899A3ED28D8@cyclops.homelinux.net]


On Jun 6, 2017, at 10:02 PM, Richard Mahn <notifications@github.com<mailto:notifications@github.com>> wrote:


@mondele<https://github.com/mondele> Do you know how he got deleted?
