### ISSUE TITLE
504 on Testing Repo

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#196]
I get a 504 on https://git.door43.org/jag3773/Testing .

**Comment by ethantkoenig** [comment]
Looks like it has to do with the sinisterly-name `content\G44870\ῥῆμα.md`. I'll try to find a fix.

**Comment by jag3773** [comment]
@ethantkoenig Ha!  It's just Greek!  What could possibly be so sinister about that?

Thanks :)

**Comment by ethantkoenig** [comment]
Upstream PR for fix: https://github.com/go-gitea/git/pull/64
