### ISSUE TITLE
Releases Page Requring Login

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#198]
For some reason visiting a releases page when not logged into DCS requires a sign in: https://git.door43.org/Door43/en_obs/releases .

Likewise, I think those outside of a particular organization get a 404 message when trying to view releases for a repo within an organization.

Desired behavior is that releases are visible to all.

**Comment by ethantkoenig** [comment]
Upstream PR: https://github.com/go-gitea/gitea/pull/1999
