### ISSUE TITLE
Increase Diff Size Limit

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#20]
It appears that gogs has a built in limit of the amount of changes it will display in a diff.  For example, https://git.door43.org/Door43/tn-en/commit/567f0857e9d7ff7dcc28072d2c798880ba61b3e4 shows `Diff Data Not Available.`  We need to increase the limit!

**Comment by jag3773** [comment]
Possibly related is https://github.com/gogits/gogs/issues/2641 .  Example of that is https://github.com/unfoldingWord/udb-en/commit/fd905e2861c22ca31eb5dccb1c9b0b72b9da7386.patch.

Note, however, that we do want the nice UI for the larger diff.  Having the '.patch' functionality would be nice be nice too.  Probably worth waiting to see if upstream writes that part.

**Comment by richmahn** [comment]
Completed on test.door43.org:3000 in the develop branch
