### ISSUE TITLE
Timeout on en_tw bible folder load

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#200]
Trying to load https://git.door43.org/Door43/en_tw/src/master/bible is timing out.  You can load the sub-folders without much trouble, https://git.door43.org/Door43/en_tw/src/master/bible/kt or https://git.door43.org/Door43/en_tw/src/master/bible/other.  The main repo loads fine too: https://git.door43.org/Door43/en_tw/

**Comment by richmahn** [comment]
I forked en_tw, renamed config.yaml in the bible/ directory and now it works. Looks like it is trying to do something with the config.yaml file. That is odd as it shouldn't be showing YAML files in a directory listing, unless Gitea shows the content of a file like it does a README file if there is only one?

**Comment by richmahn** [comment]
Must be because the yaml file is 690k in size, takes a long time to edit even the renamed copy. Odd that the file listing page tries to load it.

Can see the bible/ directory load in my repo: https://git.door43.org/richmahn/en_tw/src/master/bible

**Comment by ethantkoenig** [comment]
I believe this is related to https://github.com/go-gitea/git/pull/66, which would explain why renaming the file fixed the problem. I'll merge in changes from upstream.

**Comment by richmahn** [comment]
Fixed in Gogs develop branch, to be deployed to production
