### ISSUE TITLE
500 errors on certain repos

### ISSUE THREAD

**Issue by sea-liesch** [unfoldingWord-dev/gogs#204]
When trying to access specific repos, I am getting a 500 error.
An example is: https://git.door43.org/parfait-ayanou/chw_act_text_reg

Thank you.

**Comment by jag3773** [comment]
@sea-liesch Can you list some of the other repos that are throwing the 500 errors as well so that we can verify if we have fixed the problem?

**Comment by jag3773** [comment]
There is another one at https://git.door43.org/gerdon89/bqr_act_text_ulb

**Comment by ethantkoenig** [comment]
From looking at the logs, it* seems to be a problem with our changes from #182. Looking into it now.
