### ISSUE TITLE
JSON Unmarshal error

### ISSUE THREAD

**Issue by ethantkoenig** [unfoldingWord-dev/gogs#215]
Several of these errors are appearing in the logs:

```
2017/07/10 11:05:21 [.../runtime/asm_amd64.s:514 call32()] [E] json.Unmarshal:
{"Len":1,"Commits":[{"Sha1":"520d67c17e86adc53cc46a81cc71afec9d0946b5","Message":"Add files to 'Ceb_Mast_Checker_L3N'\n
Updated Cebuano Legal and Doctrinal Statement for Level 3 Checking of Ephesians, 1u00262 Thessalonians, 1u00262 Timothy\n","AuthorEmail":"acclo4lyf@gmail.com","AuthorName":"xammi"}],"CompareUrl":"xammi/ceb_legal_statements/compare/3ae3032289b5211dc29698ae217b660b939ada82...520d67c17e86adc53cc46a81cc71afec9d0946b5","Avatars":null}
ERROR: invalid character '\n' in string literal
```

The error is coming from [here](https://github.com/unfoldingWord-dev/gogs/blob/develop/modules/templates/helper.go#L320).

This is caused by the new line in the `"Message"` field. Note the newline is printed as an actual newline, between `\n` and `Updated`; the rendered `\n`s correspond to the two-character sequence `(forward-slash)n`

The JSON comes from the `content` column of the `action` table. This column is populated by calling `json.Marshal(..)` ([here](https://github.com/unfoldingWord-dev/gogs/blob/develop/models/action.go#L581)), which doesn't output newlines, so I'm confused how the newline got there in the first place. Have not been able to reproduce.

**Comment by ethantkoenig** [comment]
Another one (probably related):
```
2017/08/03 16:32:12 [.../runtime/asm_amd64.s:514 call32()] [E] json.Unmarshal:
{"Len":1877,"Commits":[{"Sha1":"ff44e050a4d17c0930aa7a6422c2135265f4b1e1","Message":"Sat Nov 19 2016 21:09:46 GMT-0500 (Haiti Standard Time)\n","AuthorEmail":"you@example.com","AuthorName":"iceboxpr765","CommitterEmail":"you@example.com","CommitterName":"iceboxpr765","Timestamp":"2016-11-20T02:09:46Z"},{"Sha1":"3503009eea308d5ae7527916177af1d928d78fe9","Message":"Sat Nov 19 2016 21:08:42 GMT-0500 (Haiti Standard Time)\n","AuthorEmail":"you@example.com","AuthorName":"iceboxpr765","CommitterEmail":"you@example.com","CommitterName":"iceboxpr765","Timestamp":"2016-11-20T02:08:42Z"},{"Sha1":"a20b632ed6695f3b42eefb18720fdeba934ed24e","Message":"Sat Nov 19 2016 21:08:40 GMT-0500 (Haiti Standard Time)\n","AuthorEmail":"you@example.com","AuthorName":"iceboxpr765","CommitterEmail":"you@example.com","CommitterName":"iceboxpr765","Timestamp":"2016-11-20T02:08:41Z"},{"Sha1":"7933d90587d1e587ff4c6c805747a5f99c36571b","Message":"Sat Nov 19 2016 21:08:12 GMT-0500 (Haiti Standard Time)\n","AuthorEmail":"you@example.com","AuthorName":"iceboxpr765","CommitterEmail":"you@example.com","CommitterName":"iceboxpr765","Timestamp":"2016-11-20T02:08:12Z"},{"Sha1":"fba53256acc4ca1ca19d82176c26178d9ccdbc1e","Message":"Merge branch 'master' of C:\Users\mast\AppData\Local\translationstudio\temp\es-419_bible_tw-25\es-419_bible_tw\n","AuthorEmail":"you@example.com","AuthorName":"iceboxpr765","CommitterEmail":"you@example.com","CommitterName":"iceboxpr765","Timestamp":"2016-11-20T02:08:11Z"}],"CompareURL":"iceboxpr765/es-419_bible_tw/compare/29bdc8cd70b3d7532bf859d8fb9ff3ffd1ed99fc...ff44e050a4d17c0930aa7a6422c2135265f4b1e1"}
ERROR: invalid character 'U' in string escape code
```

**Comment by ethantkoenig** [comment]
@richmahn @jag3773 There are several rows the `action` table (e.g. ids 20237, 50484) whose `contents` field contain invalid JSON (bad escape chars). Have we made any manual additions/modifications to the `action` table? Also, would you like me to make manual corrections?

**Comment by ethantkoenig** [comment]
The most recent row with invalid JSON was added 05/13/17, and about a dozen were added the day before at the same second (05/12/2017 @ 8:04:52pm (UTC)). Does this bring anything to mind?

**Comment by jag3773** [comment]
I'm not sure @ethantkoenig.  Only thing I can think of is a bug in the code we were running prior to 5/13 but maybe there was something else going on?  Could maybe have been related to the transition to AWS as well.

Yes, let's fix these ones manually and see if any other pop up.

**Comment by jag3773** [comment]
Just reviewed the logs again and I didn't see any more instances of this error.
