### ISSUE TITLE
Formatting of Issues

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/gogs#217]
I just tried putting in two issues for the ULB and UDB. In the past we could copy and paste text  and it would keep the line breaks. 

	\v 7 Instead, he gave up everything.
	\q He took on the qualities of a servant,
	\q and he became a human being.
	\q He shared the nature of human beings, though he was still God,

Now it does not allow simple line breaks. Either everything is all in one line, or I need to put in double line breaks.

\v 7 Instead, he gave up everything. \q He took on the qualities of a servant, \q and he became a human being. \q He shared the nature of human beings, though he was still God,

	OR

\v 7 Instead, he gave up everything.

\q He took on the qualities of a servant,

\q and he became a human being.

\q He shared the nature of human beings, though he was still God,

**Can you please format the issue editor so it is back to the way it was?**

**Comment by jag3773** [comment]
@ChrisJarka That is how markdown works, you need double line breaks to spilt paragraphs.

I think what you are trying to do is insert a "code-block" which you can do with triple back ticks (`) to open and close the section.  Looks like you have done that in this issue in your post.
