### ISSUE TITLE
Not rendering Greek/Hebrew text in issue comments

### ISSUE THREAD

**Issue by ethantkoenig** [unfoldingWord-dev/gogs#218]
See https://git.door43.org/Door43/en_ulb/issues/189

**Comment by ethantkoenig** [comment]
Non-latin1 text is not stored correctly in MySQL (a query like `SELECT id, content FROM comment WHERE issue_id=1141` confirms).

We will need to update MySQL's default charset to support non-latin1 text in the future; I'm not sure if existing text is recoverable.

Reference: https://dev.mysql.com/doc/refman/5.7/en/charset.html

**Comment by jag3773** [comment]
I've updated the database and tables  to use character set `utf8mb4` and collation `utf8mb4_unicode_ci`.

Remaining item is to set the defaults on the RDS to the above, which requires a reboot of the instance, so I'll set this to happen during a maintenance window.
