### ISSUE TITLE
Update codebase to Gitea 1.2

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#220]
Upgrade our DCS codebase to include Gitea 1.2 enhancements.

**Comment by jag3773** [comment]
@ethantkoenig Would you be able to do this code merge for us when Gitea v1.2.0 is released?

**Comment by ethantkoenig** [comment]
@jag3773 Sure. I assume you want to wait for the stable v1.2, as opposed to the already-ready release candidates?

**Comment by jag3773** [comment]
Correct

**Comment by jag3773** [comment]
@ethantkoenig Can you update our codebase to the recently released 1.2.1?

**Comment by ethantkoenig** [comment]
@jag3773 Done, pushed to the [v1.2](https://github.com/unfoldingWord-dev/gogs/tree/v1.2) branch.
