### ISSUE TITLE
Update Text on Main Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#228]
I have updated the About page that we have in the wiki at https://git.door43.org/Door43/pages/wiki/Welcome-to-Door43-Content-Service%21 .  We need to update the front page of the site with these updates.

## Notes

* [ ] Remove "Welcome to" so the logo is first on the page
* [ ] The last section "Conversion to Door43" should be on it's own full-width row, below the split row of "Get Started" and "Communication"
* [ ] I'd like the octicon-person icon to the left of "Get Started"
* [ ] I'd like the octicon-comment-discussion icon to the left of "Communication"
* [ ] I'd like the octicon-gear icon to the left of "Conversion to Door43"

**Comment by ChrisJarka** [comment]
Great layout! Love the graphic.

It would be nice, if possible, to have all of the links open a new page/tab/window.

Personally, I hate it when the page I'm reading for instructions gets lost because I clicked on a link for more information. :)
