### ISSUE TITLE
Link to About DCS Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#233]
The header link, "About DCS", should link to the main page that a user sees if they are not logged in (e.g. the page shown in https://github.com/unfoldingWord-dev/gogs/pull/230 ).

I think we need to provide a new URL for this page so that it functions when logged in, possibly /about_dcs .  Once that is setup the link in the header and anywhere else the link exists would need updated to point at that location.

**Comment by jag3773** [comment]
@ethantkoenig Can you make this happen without too much hacking?

**Comment by ethantkoenig** [comment]
@jag3773 I'm still deciding whether adding an `/about` page that always shows the home page (regardless of whether user is logged in) makes sense upstream. But even if we don't make the change upstream, I don't think it will be too big of a hack.
