### ISSUE TITLE
Bump Font Size on Main Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#239]
The default font size on the main page (also the /about) page needs to be bumped up a little bit.  I'm showing that it's set to 14px right now, increasing this to 16px makes it much easier to read.

**Comment by ethantkoenig** [comment]
@jag3773 Right now, the default font size for all text is 14px (this is set by Semantic UI). Do we only want to increase the font size of the home/about page's text, or increase the default font size for *all* text?

**Comment by jag3773** [comment]
The calculated text size of a README file comes out to 16px whereas the main page has it as 14px.  I think the default is fine but for that main page a slightly larger font size would make it a lot more readable.
