### ISSUE TITLE
Merge Gitea 1.3.2

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#246]
https://github.com/go-gitea/gitea/releases/tag/v1.3.1

**Comment by jag3773** [comment]
@ethantkoenig If you can get our codebase updated then I'll run the new code through our testing and hopefully make an update to our site.  The URL issues that you fixed in https://github.com/go-gitea/gitea/pull/3100 was the only blocker in the previous binary.

**Comment by ethantkoenig** [comment]
@jag3773 I think we should wait until 1.3.2 is released (will be soon), see https://github.com/go-gitea/gitea/issues/3155

**Comment by ethantkoenig** [comment]
I've created the [v1.3](https://github.com/unfoldingWord-dev/gogs/tree/v1.3) branch, and merged the 1.3.2 release into it.
