### ISSUE TITLE
Figure out what happened to Release Ordering

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#249]
The releases that show up at the top of https://git.door43.org/Door43/en_ulb/releases were actually created a long time ago.  Somehow the update to 1.4.0 messed up their date stamp, but I'm not sure how.

**Comment by ethantkoenig** [comment]
I'm guessing this is the culprit: https://github.com/unfoldingWord-dev/gogs/blob/develop/models/migrations/v39.go

**Comment by ethantkoenig** [comment]
See https://github.com/go-gitea/gitea/issues/2154 for a discussion of the decision to enforce a 1-to-1 correspondence between tags and releases.

**Comment by jag3773** [comment]
mmm... OK.  Sounds right but I'm wondering if there is a way that we can change the date on those so that they don't show up first?  There are a handful of repos that probably have this issue.
