### ISSUE TITLE
1.4.0 release does not include migration fix

### ISSUE THREAD

**Issue by ethantkoenig** [unfoldingWord-dev/gogs#250]
Our 1.4.0 release does *not* include the fix for https://github.com/go-gitea/gitea/issues/3155.

We may have to resort to some trickery to get our database back to a valid state. I will investigate more thoroughly when I get the chance.

**Comment by jag3773** [comment]
What's the status of this?

**Comment by ethantkoenig** [comment]
I believe the upstream fixes took care of everything for us, but I'll double check.

**Comment by ethantkoenig** [comment]
Confirmed that this is resolved.
