### ISSUE TITLE
Support auto-complete for @ symbol

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#251]
When writing in Issues and PRs it would be great if the @ symbol populated the list of folks that could be tagged, much like Github does.

I think the list of users that Github allows are the creator of the issue and anyone a part of the team/org that owns the repo (plus collaborators).  Essentially, those with Write access or the creator of the issue become the options.

**Comment by ethantkoenig** [comment]
There's already been an upstream PR for this: https://github.com/go-gitea/gitea/pull/3136

**Comment by jag3773** [comment]
Fixed in latest release!  Thanks!
