### ISSUE TITLE
500 On Branches

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#259]
I'm seeing 500 errors when trying to browse other branches in DCS.

For instance, I created a branch with a new folder and file, which you can see here: https://git.door43.org/Door43/en_uhg/src/branch/front_matter/content/front/title.md.  However, if I try to navigate to that, like this link: https://git.door43.org/Door43/en_uhg/src/branch/front_matter/content , it shows a 500 error.  I think that it must not be "falling back" to the `master` branch when the specified branch doesn't have the changes.

**Comment by ethantkoenig** [comment]
As far as bugs go, this is about as good as we can hope for; this means we can finally reproduce the `GetCommitsInfo` errors that have appearing in our logs

**Comment by ethantkoenig** [comment]
https://github.com/go-gitea/git/pull/98

**Comment by ethantkoenig** [comment]
Fixed with the 1.5 release
