### ISSUE TITLE
Include License File in New Repos

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#3]
Every repo created through the Gogs interface should be initialized with a LICENSE file that contains the English CC BY SA human readable license.  This should result in a fixed field on the new repo creation page that is statically set to CC BY SA.

This should work: https://github.com/Door43/d43-en/blob/master/legal/license.txt -- but update that to MarkDown format please.

**Comment by jag3773** [comment]
Note that there is a Markdown version here: https://git.door43.org/Door43/tw-en/src/master/LICENSE.md .  You can just copy that.

**Comment by richmahn** [comment]
Can be seen @ http://test.door43.org:3000/repo/create
