### ISSUE TITLE
License File Tweaks

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#38]
The license file that is automatically added to repos needs the following changes:

* [x] named LICENSE.md
* [x] Only include the CC-BY-SA text (like https://git.door43.org/Door43/tq-en/src/master/LICENSE.md).

**Comment by jag3773** [comment]
@richmahn feel free to create the said file in the en-legal repo if it's easier that way.  The one currently in there has extra information that is not desirable.

**Comment by richmahn** [comment]
Done on development.
