### ISSUE TITLE
New Repo: Language Field

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#4]
Update the Language field on the new repo creation screen to key off our list of languages in tD, source at http://td.unfoldingword.org/exports/langnames.json.

We may want to implement this as a new table in the DB for easier updating?  Otherwise we would have to rebuild the gogs binary every time we want to update the list of languages.  Or, we could set the field to key off a cached version of that langnames.json file?

In any case, the field should work like it does on Door43 and/org tD, with typeahead-like functionality.

**Comment by richmahn** [comment]
Question: while this field could changed to use natural languages, what would be done with the selection once the repo form is selected? Just stored in a column in a database for administration purposes? Put into the README.md template? Currently it would be lost even if the page could submit a language code.

**Comment by richmahn** [comment]
Would we want to tack the language selected onto the front/end of the repo name?
