### ISSUE TITLE
Change the "HELP" menu to our own "Help" and not Gogs and make it for logged in users

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/gogs#41]
The "Help" menu item at the top of the page when not logged in goes to gogs.io which is help for developers/installers. We need this to be for our own site for content technicians and other users of uW. We need the following:

- [x] Content for the help page
- [x] Make the help link go to a template file locally
- [x] Make it so logged in users also have a help option

**Comment by jag3773** [comment]
Merge About and Help and point it toward the content of the main page.

**Comment by ChrisJarka** [comment]
What about putting a link to Slack and Discourse and maybe the helpdesk email address/link?
Or, is there a way that the page can be designed like the Gogs help page just with 'our' topics?

**Comment by richmahn** [comment]
@ChrisJarka Right now I point the "About Door43" to https://git.door43.org/Door43/pages/wiki/Welcome-to-Door43%21 . Any one with access can change it. It won't be the exact same as the landing page someone gets when not logged in...I have to change that in another file, but will watch the Wiki page to see what to put into the wiki page.
