### ISSUE TITLE
Formatting of bullet items is not quite right

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/gogs#44]
Sometimes formatting is applied and sometimes not. See list at bottom of screen shot. The first item is italicized and the others are not.

![image](https://cloud.githubusercontent.com/assets/5262964/14997855/cf711c42-114e-11e6-89a1-a8f32bf879d7.png)

**Comment by phillip-hopper** [comment]
@jag3773: This is still happening.

**Comment by richmahn** [comment]
The markdown processor is a third-party Go library (where as the Editor for MD is yet another library and it shows it right in its preview). If you put * (asterisks) around the link markdown, it does work for emphasis. Can we write it with * <text> * instead of _ <text> _ ?

**Comment by richmahn** [comment]
Scratch that last comment about how the Preview (eye icon) of the MD editor does it right. It also leaves the _'s. With two totally separate libraries written in different code and one for back end and one for front end, I wonder if _(title)[link]_ is not a valid markdown combination. If we really need it, let me know.

**Comment by richmahn** [comment]
Made an issue with the Markdown render plugin that Gogs uses: https://github.com/russross/blackfriday/issues/278
