### ISSUE TITLE
Write Viewer for YAML Front Matter

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#45]
The top of every tA page includes a section of front matter (metadata) that is written in YAML.  Since Pandoc supports this in output documents, it seems like adding a nice viewer for this into the Markdown viewer may be a nice route to go.  Right now the YAML part looks very pathetic, see https://git.door43.org/jag3773/NotesTest/wiki/Test.

If there are no better ideas, let's plan to do this.

**Comment by jag3773** [comment]
@richmahn Note that Github does this, see https://github.com/unfoldingWord/unfoldingWord.github.io/blob/master/pages/content/tn.md as an example.

**Comment by richmahn** [comment]
@jag3773: Ok, noted. Now that I know how this is relevant (I never looked at a page of tA in Epad before :blush:) I see why this is important. So I assume all YAML gets left in the converted tA page, as is, right?

**Comment by richmahn** [comment]
Was able to quickly implement this, using https://github.com/go-yaml/yaml

Currently implemented at test.door43.org:3000 (example: http://test.door43.org:3000/richgogs/TestRepo2/src/master/test.md)

**Comment by ChrisJarka** [comment]
Thank you Rich! We put a lot of thought process into the information on the YAML and I'm glad to see that it will be usable in GO language too.
