### ISSUE TITLE
Copy Legal Info Over

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#5]
We need to copy over all the legal information from DW door43.org.  See https://door43.org/en/legal/home.

Those pages should be copied into https://git.door43.org/Door43/en-legal/wiki.  We can link to them from elsewhere in the site once they are setup there.

**Comment by richmahn** [comment]
I have already made a Copyrights & License and Statement of Faith in the wiki on both prod and test. Needs a "Terms & Conditions" page and the "Statement of Faith" page has a link at the bottom that currently goes to the old door43.org for 'Translation Guidelines'

**Comment by richmahn** [comment]
See http://test.door43.org:3000/user/sign_up for what needs to link where.

**Comment by jag3773** [comment]
@richmahn please copy over the Translation Guidelines to Door43 / en-legal wiki
