### ISSUE TITLE
Request to Publish Feature

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#50]
Move the request to publish process into Gogs, making use of Issues in a "rtp" repository.

## Initial Components

* JS frontend for the form, using the API to seed the language and published docs fields.  Minimal intrusion into Gogs code.
* Requestor must have a Door43 account (be logged in)
* Requests submitted as an Issue to the uW RtP repo (maybe https://git.door43.org/unfoldingWord/rtp/issues)
* Requests are formatted in Markdown and look good in the issue queue.
* Files may be attached to the request via the Gogs issue file attachment process.  They remain with the issue/ticket forever.
* The requestor receives and email that the issue has been created, with the link to the issue for future reference.
* The issue is assigned to the approver (Perry in this case).
* The approver may comment on the issue if anything is missing (requestor will be auto-emailed since they submitted the issue).
* Approver may approve the request by adding a label and/or assigning to the publishing tech.
* After publishing, tech asks requestor for approval of published material by comment on issue.
* Issue is closed upon approval.

## Later add-ons:

* When the approver approves the issue, the publish process happens automatically and the requestor is automatically emailed to review.

## Benefits:

* We are not locked into a database schema, we can change the form fields at any time.
* The issues are persistent and public, even after closed.
* The issues are easy to review.
* Use existing infrastructure.

**Comment by phillip-hopper** [comment]
I like it. :+1:

**Comment by richmahn** [comment]
Same here :+1:

**Comment by pjoakes** [comment]
We need the file attachment now, not later, for the signed documents. The files need to go into a repository where I can **quickly and easily** find them.

**Comment by jag3773** [comment]
A quick and dirty prototype is available by visiting https://git.door43.org/unfoldingWord/rtp/issues/new .

**Comment by ChrisJarka** [comment]
Too bad the word 'issue' could not be changed for this repo. 'Issue' has a negative meaning for me. Do you know if the rest of the world will view it with the same meaning?

**Comment by jag3773** [comment]
We'll find out @ChrisJarka ;)
