### ISSUE TITLE
Add Support for Tags in Content

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#51]
## Story

As a _content creator_ I want the hashtags that I'm using in my content to be clickable and colorized so that it's easy to see them and easy to see everywhere they are used.

## Notes

Each tag used should link to a page that shows every place that it occurs in that project (disambiguation page).  For example, a tag of #kingdomofgod should link to a page that shows every place that the tag is used (with links to the page it is used on).

Tags that should not receive their own disambiguation page.

* Any tag started with #v

We would also need a page that lists all tags and/or all tags for a category.  For instance, one will want to see all "Map Tags".  Possibly, this could be a single page that sorts tags alphabetically, that would accomplish sorting by category and may be sufficient.

* The above feature should work for all `lang-ubn` repos in an organization/user account
* For example, Door43/en-ubn-act and Door43/en-ubn-luk should have their tags aggregated
* The "articles" for UBN will show up in a repo named `lang-ubn-articles`, e.g. en-ubn-articles

In the **Editor view** the hashtags should show up colorized so that they stand out better against the normal next.  Perhaps use a color scheme based on type of tag (see https://git.door43.org/Door43/en-ubn/wiki/Tagging-Content-)

## Questions

* how to get to main page that lists all tags?

**Comment by Thajny** [comment]
![screen shot 2016-12-20 at 6 47 58 pm](https://cloud.githubusercontent.com/assets/21183377/21373548/7c8a53fc-c6e5-11e6-9b8a-ba052fa5b154.png)
![screen shot 2016-12-20 at 6 48 26 pm](https://cloud.githubusercontent.com/assets/21183377/21373547/7c8a0050-c6e5-11e6-9e59-5913c8e393bf.png)
![screen shot 2016-12-20 at 6 48 40 pm](https://cloud.githubusercontent.com/assets/21183377/21373549/7c8e15c8-c6e5-11e6-8bfa-bd56d99aa905.png)

**Comment by Thajny** [comment]
Notes:
- If an entry doesn't exist for a letter (IE, 'B'), then it appears opaque in the sorting bar
- Clicking on a letter in the sorting bar will turn that box blue and will only display entries of the highlighted letter (IE - selecting 'A' 'D' and 'J' will show only entries beginning in those letters).

**Comment by Thajny** [comment]
![screen shot 2017-01-04 at 3 40 34 pm](https://cloud.githubusercontent.com/assets/21183377/21660295/6e6b4f6e-d294-11e6-9db9-c530bd0e2534.png)
![screen shot 2017-01-04 at 3 41 09 pm](https://cloud.githubusercontent.com/assets/21183377/21660296/6e7bab5c-d294-11e6-9f37-8ea8ecdaed33.png)
![screen shot 2017-01-04 at 3 41 32 pm](https://cloud.githubusercontent.com/assets/21183377/21660298/6e7d0e5c-d294-11e6-8cf0-b96d4ddd0af8.png)

**Comment by jag3773** [comment]
👍
