### ISSUE TITLE
Ordering of content pages

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/gogs#53]
Is it possible to order the content pages in a repo in alpha (the default) or by change date?

So that the listing on this page https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content could be changed so that the most recently changed would be at the top of the list?

See closed https://git.door43.org/Door43/en-ta/issues/5

**Comment by richmahn** [comment]
It currently isn't possible, @ChrisJarka . It isn't even possible on https://github.com which this is try to be somewhat similar to.

**Comment by richmahn** [comment]
Not saying it is a bad idea, but would require some reworking of the GUI and code.

**Comment by ChrisJarka** [comment]
Oh well, maybe put on the list of things to do when there is nothing else to do. :) ROFL
