### ISSUE TITLE
Build Out Missing API Components

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#55]
Potentially, there are missing features in the API that we need to implement in order to support current translationStudio needs and future translationManager needs.  We need to discuss this with @klappy and @neutrinog to see what they think.

Here is a list for starters:
- [x] Users
- [x] Starring - we need to get read/write what repos a user has starred
- [x] Watching - need read/write for what repos a user is watching
- [x] Issues - we need API support to add, edit, close, remove issues
- [x] Organization functions -  We need to add, modify, delete members, teams, webhooks.
- [x] Webhooks - we need full API support to add, modify, remove webhooks for repos or organizations
- [x] Repository functions - We need to be able to modify repo configuration, such as create/modify Releases, manage collaborators, create fork, etc.

I believe current progress is recorded in https://github.com/gogits/go-gogs-client/wiki.

**Comment by neutrinog** [comment]
I'm throwing word count in here just so we/I don't forget.

**Comment by neutrinog** [comment]
@jag3773 yes sorry I wrote that before I realized what this issue was really about :P

**Comment by ethantkoenig** [comment]
Could you be a little more specific about the endpoints you would like me to add? For example, "Issues" is in the checklist above,but there are already a number of API endpoints for issues (see [the wiki](https://github.com/gogits/go-gogs-client/wiki/Issues)). Are there additional ones that you need?

**Comment by ethantkoenig** [comment]
@jag3773 Do we need to support *removing* issues (as opposed to just closing them)? Right now, neither Github nor Gogs/Gitea support removing issues.

**Comment by ethantkoenig** [comment]
I believe that the endpoints we need for issues already exist (see [Issues](https://github.com/gogits/go-gogs-client/wiki/Issues)). Let me know if I'm missing something.

**Comment by jag3773** [comment]
If it's there, great!

**Comment by ethantkoenig** [comment]
Checking off webhooks, because the endpoints already exist for repos, and the ones for organizations are covered by the "Organizations" item.

**Comment by ethantkoenig** [comment]
@jag3773 All of the requested endpoints have been merged into `gitea:master`.
