### ISSUE TITLE
Add Webhook to Post to Amazon SQS & SNS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#59]
We need to add a Amazon SQS & SNS webhook/service.  Github has a setup for this, although I don't think their code is available for it anywhere.  See this link for how it should look (https://github.com/unfoldingWord-dev/gogs/settings/hooks/new?service=sqsqueue).

Also, these links might be helpful for actually writing the code for it:

- https://github.com/aws/aws-sdk-go
- https://github.com/goamz/goamz/tree/master/sqs
- http://stackoverflow.com/questions/26041847/github-webhook-not-posting-to-amazon-sqs-queue-due-to-unknownoperationexception

**Comment by bspidel** [comment]
Last time I tried, I did not have access to sqs


Bruce Spidel

E-Mail: bruce.spidel@gmail.com
Mobile: (812) 239-2086
Skype: bruce.m.spidel

**Comment by richmahn** [comment]
I'll need access too. I also need to understand if this is just something each user will have to set up for each of their repositories, or just have it happening for all repositories, where it triggers whenever a commit/push/pull request is made? On github it is up to the user to set it up.

**Comment by jag3773** [comment]
* I added SNS to the to-do.  The setup should be much the same but SNS is a separate AWS service.
* These should be user configurable webhooks.  But we will set them up on all repos by default.  User's can disable them if they wish.
