### ISSUE TITLE
Use S3 For Files

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#71]
## Story

As an _admin_ I would like files to be stored and served from AWS S3 so that I don't have to use local storage on my server.
## Notes

Mostly this https://github.com/gogits/gogs/issues/2904 .

Stop gap might simply be to create a cron that syncs the attachments to an S3 bucket on an interval.  This would give us a persistent backup of the attachments and _might_ prepare for a switch to using S3 directly for attachments.

**Comment by ethantkoenig** [comment]
@jag3773 If the end goal is to have the content stored in S3, would https://github.com/s3fs-fuse/s3fs-fuse meet our needs? It would allow us to mount an S3 bucket as a virtual drive.

**Comment by jag3773** [comment]
Yes, that would work but it's an extra dependency that I'd rather not have.  Would great if Gogs just interfaced directly with S3.  Seems like there is probably a Go S3 library out there somewhere...

**Comment by jag3773** [comment]
Deprecated by #110
