### ISSUE TITLE
Search for Issues

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#82]
## Story

As a _user_ I want to search for specific issues so that I don't have to manually look through them.
## Notes

Should work just like Github.  Need to check upstream Gogs for this request too.

**Comment by ethantkoenig** [comment]
Can I take this?

**Comment by phillip-hopper** [comment]
@ethantkoenig I think this needs to be defined more specifically before work starts. "Just like Github" needs to be defined in detail. Perhaps you could work on your test-driven-development skills, and write a set of failing tests that demonstrates how it should work. What so you thing @jag3773?

**Comment by PhotoNomad0** [comment]
Works on https://aws.door43.org/Door43/en-uhg/issues?type=all&state=open&labels=0&milestone=0&assignee=0&q=suffix
