### ISSUE TITLE
Make a page to list all tags

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#85]
This is the top level page that lists all tags for a UBN project.

From issue #51:
We would also need a page that lists all tags and/or all tags for a category. For instance, one will want to see all "Map Tags". Possibly, this could be a single page that sorts tags alphabetically, that would accomplish sorting by category and may be sufficient.

* The above feature should work for all lang-ubn repos in an organization/user account
* For example, Door43/en-ubn-act and Door43/en-ubn-luk should have their tags aggregated
* The "articles" for UBN will show up in a repo named lang-ubn-articles, e.g. en-ubn-articles

The link to this page should be in every repo that is a part of the `lang-ubn` system, next to the "Wiki" tab there should be a "Hashtags" link (with a hashtag icon from font-awesome).

URL would be `lang-ubn`/hashtags

**Comment by phillip-hopper** [comment]
Blockec by unfoldingWord-dev/door43.org/issues/330
