### ISSUE TITLE
Collaborative Editor

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#92]
## Story

As a *content creator* I want to be able to work on a page with someone else at the same time so that we can collaborate on the content.

## Notes

Let's try implementing https://togetherjs.com/ as a test to see if it will meet the needs of the UBN/UBC team.  Another potential option would be https://hypothes.is/ .  This is not quite a collaborative editor but it does allow collaborative comments that could eventually be turned into the content of the page.

## Definition of Done

* [x] togetherjs deployed to the *test* Gogs site
* [x] Implementation tested on Edit pages on Test site:
  * [x] By developer
  * [x] By PO
* [x] Scenario tested where 1 person is editing a doc and another user tries to edit the same doc (what happens? is there a prompt to collaborate?  Or nothing?)
  * Nothing happens.

**Comment by richmahn** [comment]
PR #113

**Comment by richmahn** [comment]
Come collaborate with me! http://test.door43.org:3000/richmahn/en-ubn-act/_edit/master/content/act/01.md#&togetherjs=7ynDViEIrB

**Comment by phillip-hopper** [comment]
Works good but not perfect. I tested it between 2 computers, one Windows 10 and the other Xubuntu 16.04. From my experimenting I found 2 issues:

1. It doesn't work on a new file. The file has to be saved to the repository before collaboration works.
2. Only the person who started the collaboration can commit. The others get `Invalid csrf token` when trying to save.

**Comment by richmahn** [comment]
Ah, that would make sense on #2 that only the person who started it can commit, because what happens when someone joins is that ALL input fields on the page, including hidden fields, get a copy of the person who was in the collaboration first. I was wondering if there is a way to specify what fields can be copied between people.

As for #1, I will see about not showing the button on the Create New file page.

**Comment by phillip-hopper** [comment]
I was opening the collaboration on the second computer using the "Invite a friend" link.

**Comment by richmahn** [comment]
I'm pretty satisfied with the general configuration of TogetherJS working for us. This can be looked at by you @jag3773 on test.door43.org:3000 to see what you think. Let me know if you want to set up a session where we do some collaboration together.

**Comment by jag3773** [comment]
Works for me, even if the second person commits the file.  However, would be nice if togetherjs updated all participants when the file is saved.  Currently, only the person who pushed the commit button gets the page updated, the others do not.  Also, the commit message input box was not synchronized in my testing.

I think this is good enough to pass on to the TD to test and see if it is usable for them.
