### ISSUE TITLE
Change the identification of the Issue tab for the R2P Form Repo

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/gogs#99]
Is it possible that the 'issue' tab be changed to 'submission' or 'request' or 'submit' for this repo only? 

https://git.door43.org/Door43/SourceTextRequestForm/issues/new

**Comment by jag3773** [comment]
This would require a hack that I'm not comfortable making.  Someday we may have a custom form that will make the submission process easier, I'd rather put effort into developing that.
